apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
  labels:
    app: wisecow
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: gcr.io/pure-spirit-123456-m1/wisecow:latest  # Update with your image name
        ports:
        - containerPort: 80  # Port your application listens to
        env:
        - name: ENV_VAR_NAME  # Example of setting environment variables
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
      imagePullSecrets:  # Optional, if using private images
      - name: regcred  # This should match the secret name for your container registry
