apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 3  # Increase replicas for better availability (adjust as needed)
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
          image: meeramohan323/wisecow:latest  # Ensure this is correct
          ports:
            - containerPort: 4499  # Keep the container port as is
          resources:  # Optional: Define resource requests and limits
            requests:
              memory: "256Mi"  # Minimum memory required
              cpu: "500m"      # Minimum CPU required
            limits:
              memory: "512Mi"  # Maximum memory
              cpu: "1"         # Maximum CPU
