apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  labels:
    app: wisecow
spec:
  type: LoadBalancer  # Use LoadBalancer to expose the service externally
  ports:
    - port: 80         # The port that will be exposed externally
      targetPort: 4499 # The port your container is listening on
  selector:
    app: wisecow       # This selector should match your deployment labels
