apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80           # Port exposed by the service
      targetPort: 4499   # Port of the container
  type: NodePort         # Expose service on a port
