name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  pull_request:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: meeramohan323/wisecow:latest  # Change this to your Docker Hub repo

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'  # Use 'latest' to always get the latest version

      - name: Create kube and minikube directories
        run: |
          mkdir -p $HOME/.kube
          mkdir -p $HOME/.minikube/profiles/minikube

      - name: Set kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
          echo "${{ secrets.MINIKUBE_CLIENT_CERT }}" | base64 --decode > $HOME/.minikube/profiles/minikube/client.crt
          echo "${{ secrets.MINIKUBE_CLIENT_KEY }}" | base64 --decode > $HOME/.minikube/profiles/minikube/client.key
          echo "${{ secrets.MINIKUBE_CA_CERT }}" | base64 --decode > $HOME/.minikube/ca.crt  # If required

      # Debugging steps
      - name: Check if kubeconfig exists
        run: |
          if [ -f $HOME/.kube/config ]; then
            echo "Kubeconfig exists."
          else
            echo "Kubeconfig does not exist."
          fi

      - name: Check if minikube client cert exists
        run: |
          if [ -f $HOME/.minikube/profiles/minikube/client.crt ]; then
            echo "Minikube client cert exists."
          else
            echo "Minikube client cert does not exist."
          fi

      - name: Check if minikube client key exists
        run: |
          if [ -f $HOME/.minikube/profiles/minikube/client.key ]; then
            echo "Minikube client key exists."
          else
            echo "Minikube client key does not exist."
          fi

      - name: Check if minikube CA cert exists
        run: |
          if [ -f $HOME/.minikube/ca.crt ]; then
            echo "Minikube CA cert exists."
          else
            echo "Minikube CA cert does not exist."
          fi

      - name: Change permissions for kubeconfig
        run: chmod 644 $HOME/.kube/config

      - name: Change permissions for minikube client cert
        run: chmod 644 $HOME/.minikube/profiles/minikube/client.crt

      - name: Change permissions for minikube client key
        run: chmod 600 $HOME/.minikube/profiles/minikube/client.key

      - name: List kube directory contents
        run: ls -la $HOME/.kube

      - name: List minikube directory contents
        run: ls -la $HOME/.minikube/profiles/minikube

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
