name: CI/CD for Wisecow Application

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Minikube
      - name: Start Minikube
        run: |
          minikube start --driver=docker

      # Step 3: Set up kubeconfig and certificates
        env:
          HOME: /home/runner  # Set the home directory for the runner
        run: |
          # Create necessary directories
          mkdir -p $HOME/.minikube/profiles/minikube
          mkdir -p $HOME/.kube

          # Decode the secrets and create the certificate files
          echo "${{ secrets.MINIKUBE_CA_CERT }}" | base64 -d > $HOME/.minikube/ca.crt
          echo "${{ secrets.MINIKUBE_CLIENT_CERT }}" | base64 -d > $HOME/.minikube/profiles/minikube/client.crt
          echo "${{ secrets.MINIKUBE_CLIENT_KEY }}" | base64 -d > $HOME/.minikube/profiles/minikube/client.key

          # Set appropriate permissions
          chmod 600 $HOME/.minikube/profiles/minikube/client.crt
          chmod 600 $HOME/.minikube/profiles/minikube/client.key
          chmod 600 $HOME/.minikube/ca.crt

          # Set up kubeconfig file
          cat <<EOF > $HOME/.kube/config
apiVersion: v1
clusters:
- cluster:
    certificate-authority: $HOME/.minikube/ca.crt
    server: https://127.0.0.1:56623  # Adjust this if your Minikube API server runs on a different port
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: $HOME/.minikube/profiles/minikube/client.crt
    client-key: $HOME/.minikube/profiles/minikube/client.key
EOF

      # Step 4: Apply the deployment
      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f deployment.yaml

      # Step 5: Check the status of the deployment (optional)
      - name: Check Deployment Status
        run: |
          kubectl get pods
          kubectl get services
